create extension if not exists "uuid-ossp";

create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, email text not null, phone text, avatar_url text, job_title text, department text, company_name text, work_location text, employee_id text, role text not null default 'Viewer' check (role in ('Super Admin','Admin','Room Operator','Viewer')), status text not null default 'Active', bio text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), last_login_at timestamptz);
create table if not exists rooms (id bigint generated by default as identity primary key, name text not null, location text, capacity integer, mode text default 'Available', temperature numeric, humidity numeric, network_status text, power_status text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists devices (id bigint generated by default as identity primary key, room_id bigint references rooms(id) on delete cascade, name text not null, category text, manufacturer text, model text, connection_type text, state text default 'Offline', health text default 'Unknown', ip_address inet, last_updated timestamptz default now(), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists device_status_history (id bigint generated by default as identity primary key, device_id bigint references devices(id) on delete cascade, state text not null, details jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists room_states (id bigint generated by default as identity primary key, room_id bigint references rooms(id) on delete cascade, temperature numeric, humidity numeric, network_status text, power_status text, system_health text, created_at timestamptz default now());
create table if not exists automations (id bigint generated by default as identity primary key, name text not null, description text, trigger_type text default 'Manual', is_active boolean default true, configuration jsonb default '{}'::jsonb, last_run timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists automation_runs (id bigint generated by default as identity primary key, automation_id bigint references automations(id) on delete set null, room_id bigint references rooms(id), executed_by uuid references profiles(id), status text, details jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists activity_logs (id bigint generated by default as identity primary key, room_id bigint references rooms(id), user_id uuid references profiles(id), device_id bigint references devices(id), category text not null, action text not null, title text not null, status text not null, details text, created_at timestamptz default now());
create table if not exists notifications (id bigint generated by default as identity primary key, user_id uuid references profiles(id) on delete cascade, title text not null, message text not null, notification_type text, is_read boolean default false, created_at timestamptz default now());
create table if not exists system_settings (id bigint generated by default as identity primary key, system_name text not null, organization_name text, default_room_id bigint references rooms(id), settings jsonb default '{}'::jsonb, updated_at timestamptz default now());
create index if not exists notifications_user_unread_idx on notifications(user_id, is_read, created_at desc);
create index if not exists activity_logs_room_created_idx on activity_logs(room_id, created_at desc);

insert into rooms (name, location, capacity, mode, temperature, humidity, network_status, power_status) values ('Main Conference Room', 'HQ - 2nd Floor', 12, 'Available', 23.8, 45, 'Connected', 'Stable') on conflict do nothing;

alter table profiles enable row level security;
alter table notifications enable row level security;
create policy "users can read own profile" on profiles for select using (auth.uid() = id);
create policy "users can update own profile" on profiles for update using (auth.uid() = id);
create policy "users can read own notifications" on notifications for select using (auth.uid() = user_id);
